---
- name: Pull Docker Image from Docker Hub and Run Container
  hosts: 172.29.167.205
  remote_user: subbhashit
  become: true
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "23subbhashit/minispe"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started

    - name: Run Docker Container
      docker_container:
        name: calculatorspe
        image: "23subbhashit/minispe"
        state: started
        interactive: true
        detach: true
