---
- name: Deploy Java Application
  hosts: localhost
  remote_user: subbhashit
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "23subbhashit/minispe"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Run Docker Container
      shell: docker run -d --name calculator -p 8080:8080 23subbhashit/minispe
